"""Public framework-independent application API."""

from mediaflow.application.events import (
    AnalysisFailed,
    AnalysisSucceeded,
    ApplicationEvent,
    OutputReady,
    TaskFailed,
    TaskProgressChanged,
    TaskQueued,
    TaskStateChanged,
)
from mediaflow.application.format_availability import (
    PresetAvailability,
    PresetAvailabilityIssue,
    PresetUnavailable,
    check_preset_availability,
    require_preset_available,
)
from mediaflow.application.models import AnalysisOutcome, ApplicationSettings, DownloadArtifact
from mediaflow.application.ports import (
    Analyzer,
    CancellationToken,
    Clock,
    Downloader,
    EventPublisher,
    MediaProcessor,
    ProgressSink,
    SettingsStore,
    TaskRepository,
    TaskRepositoryConflict,
)
from mediaflow.application.use_cases import (
    AnalyzeUrl,
    CancelDownload,
    EnqueueDownload,
    GetDownloads,
    GetHistory,
    ResumeDownload,
    RetryDownload,
    TaskNotFound,
)

__all__ = [
    "AnalysisFailed",
    "AnalysisOutcome",
    "AnalysisSucceeded",
    "AnalyzeUrl",
    "Analyzer",
    "ApplicationEvent",
    "ApplicationSettings",
    "CancelDownload",
    "CancellationToken",
    "Clock",
    "DownloadArtifact",
    "Downloader",
    "EnqueueDownload",
    "EventPublisher",
    "GetDownloads",
    "GetHistory",
    "MediaProcessor",
    "OutputReady",
    "PresetAvailability",
    "PresetAvailabilityIssue",
    "PresetUnavailable",
    "ProgressSink",
    "ResumeDownload",
    "RetryDownload",
    "SettingsStore",
    "TaskFailed",
    "TaskNotFound",
    "TaskProgressChanged",
    "TaskQueued",
    "TaskRepository",
    "TaskRepositoryConflict",
    "TaskStateChanged",
    "check_preset_availability",
    "require_preset_available",
]
